<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="67140" started-at="2017-08-24T08:32:46Z" finished-at="2017-08-24T08:33:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="67140" started-at="2017-08-24T08:32:46Z" finished-at="2017-08-24T08:33:53Z">
      <class name="testcase.changeManagement">
        <test-method status="PASS" signature="preCondition()[pri:0, instance:testcase.changeManagement@7a0ac6e3]" name="preCondition" is-config="true" duration-ms="16314" started-at="2017-08-24T14:02:46Z" finished-at="2017-08-24T14:03:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="FAIL" signature="testCreateChangeTicket()[pri:0, instance:testcase.changeManagement@7a0ac6e3]" name="testCreateChangeTicket" duration-ms="50792" started-at="2017-08-24T14:03:02Z" description="-----Create Change Test Case-----" finished-at="2017-08-24T14:03:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [junk] but found [Draft]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [junk] but found [Draft]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.servicenow.applicationspecificlibraries.ChangeReusables.createChange(ChangeReusables.java:95)
	at testcase.changeManagement.testCreateChangeTicket(changeManagement.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateChangeTicket -->
      </class> <!-- testcase.changeManagement -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
